// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldReservedBy holds the string denoting the reserved_by field in the database.
	FieldReservedBy = "reserved_by"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldValor holds the string denoting the valor field in the database.
	FieldValor = "valor"
	// Table holds the table name of the product in the database.
	Table = "products"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldReservedBy,
	FieldImage,
	FieldValor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByReservedBy orders the results by the reserved_by field.
func ByReservedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedBy, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByValor orders the results by the valor field.
func ByValor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValor, opts...).ToFunc()
}
