// Code generated by ent, DO NOT EDIT.

package product

import (
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// ReservedBy applies equality check predicate on the "reserved_by" field. It's identical to ReservedByEQ.
func ReservedBy(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldReservedBy, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldImage, v))
}

// Valor applies equality check predicate on the "valor" field. It's identical to ValorEQ.
func Valor(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldValor, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldTitle, v))
}

// ReservedByEQ applies the EQ predicate on the "reserved_by" field.
func ReservedByEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldReservedBy, v))
}

// ReservedByNEQ applies the NEQ predicate on the "reserved_by" field.
func ReservedByNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldReservedBy, v))
}

// ReservedByIn applies the In predicate on the "reserved_by" field.
func ReservedByIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldReservedBy, vs...))
}

// ReservedByNotIn applies the NotIn predicate on the "reserved_by" field.
func ReservedByNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldReservedBy, vs...))
}

// ReservedByGT applies the GT predicate on the "reserved_by" field.
func ReservedByGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldReservedBy, v))
}

// ReservedByGTE applies the GTE predicate on the "reserved_by" field.
func ReservedByGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldReservedBy, v))
}

// ReservedByLT applies the LT predicate on the "reserved_by" field.
func ReservedByLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldReservedBy, v))
}

// ReservedByLTE applies the LTE predicate on the "reserved_by" field.
func ReservedByLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldReservedBy, v))
}

// ReservedByContains applies the Contains predicate on the "reserved_by" field.
func ReservedByContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldReservedBy, v))
}

// ReservedByHasPrefix applies the HasPrefix predicate on the "reserved_by" field.
func ReservedByHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldReservedBy, v))
}

// ReservedByHasSuffix applies the HasSuffix predicate on the "reserved_by" field.
func ReservedByHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldReservedBy, v))
}

// ReservedByEqualFold applies the EqualFold predicate on the "reserved_by" field.
func ReservedByEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldReservedBy, v))
}

// ReservedByContainsFold applies the ContainsFold predicate on the "reserved_by" field.
func ReservedByContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldReservedBy, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldImage, v))
}

// ValorEQ applies the EQ predicate on the "valor" field.
func ValorEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldValor, v))
}

// ValorNEQ applies the NEQ predicate on the "valor" field.
func ValorNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldValor, v))
}

// ValorIn applies the In predicate on the "valor" field.
func ValorIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldValor, vs...))
}

// ValorNotIn applies the NotIn predicate on the "valor" field.
func ValorNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldValor, vs...))
}

// ValorGT applies the GT predicate on the "valor" field.
func ValorGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldValor, v))
}

// ValorGTE applies the GTE predicate on the "valor" field.
func ValorGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldValor, v))
}

// ValorLT applies the LT predicate on the "valor" field.
func ValorLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldValor, v))
}

// ValorLTE applies the LTE predicate on the "valor" field.
func ValorLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldValor, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
