// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/family"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfirmationPresenceCreate is the builder for creating a ConfirmationPresence entity.
type ConfirmationPresenceCreate struct {
	config
	mutation *ConfirmationPresenceMutation
	hooks    []Hook
}

// SetFullname sets the "fullname" field.
func (_c *ConfirmationPresenceCreate) SetFullname(v string) *ConfirmationPresenceCreate {
	_c.mutation.SetFullname(v)
	return _c
}

// SetPhotoBase64 sets the "photo_base64" field.
func (_c *ConfirmationPresenceCreate) SetPhotoBase64(v string) *ConfirmationPresenceCreate {
	_c.mutation.SetPhotoBase64(v)
	return _c
}

// SetNillablePhotoBase64 sets the "photo_base64" field if the given value is not nil.
func (_c *ConfirmationPresenceCreate) SetNillablePhotoBase64(v *string) *ConfirmationPresenceCreate {
	if v != nil {
		_c.SetPhotoBase64(*v)
	}
	return _c
}

// SetIsConfirmed sets the "is_confirmed" field.
func (_c *ConfirmationPresenceCreate) SetIsConfirmed(v bool) *ConfirmationPresenceCreate {
	_c.mutation.SetIsConfirmed(v)
	return _c
}

// SetNillableIsConfirmed sets the "is_confirmed" field if the given value is not nil.
func (_c *ConfirmationPresenceCreate) SetNillableIsConfirmed(v *bool) *ConfirmationPresenceCreate {
	if v != nil {
		_c.SetIsConfirmed(*v)
	}
	return _c
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_c *ConfirmationPresenceCreate) SetFamilyID(id int) *ConfirmationPresenceCreate {
	_c.mutation.SetFamilyID(id)
	return _c
}

// SetNillableFamilyID sets the "family" edge to the Family entity by ID if the given value is not nil.
func (_c *ConfirmationPresenceCreate) SetNillableFamilyID(id *int) *ConfirmationPresenceCreate {
	if id != nil {
		_c = _c.SetFamilyID(*id)
	}
	return _c
}

// SetFamily sets the "family" edge to the Family entity.
func (_c *ConfirmationPresenceCreate) SetFamily(v *Family) *ConfirmationPresenceCreate {
	return _c.SetFamilyID(v.ID)
}

// Mutation returns the ConfirmationPresenceMutation object of the builder.
func (_c *ConfirmationPresenceCreate) Mutation() *ConfirmationPresenceMutation {
	return _c.mutation
}

// Save creates the ConfirmationPresence in the database.
func (_c *ConfirmationPresenceCreate) Save(ctx context.Context) (*ConfirmationPresence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfirmationPresenceCreate) SaveX(ctx context.Context) *ConfirmationPresence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfirmationPresenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfirmationPresenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConfirmationPresenceCreate) defaults() {
	if _, ok := _c.mutation.IsConfirmed(); !ok {
		v := confirmationpresence.DefaultIsConfirmed
		_c.mutation.SetIsConfirmed(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfirmationPresenceCreate) check() error {
	if _, ok := _c.mutation.Fullname(); !ok {
		return &ValidationError{Name: "fullname", err: errors.New(`ent: missing required field "ConfirmationPresence.fullname"`)}
	}
	if _, ok := _c.mutation.IsConfirmed(); !ok {
		return &ValidationError{Name: "is_confirmed", err: errors.New(`ent: missing required field "ConfirmationPresence.is_confirmed"`)}
	}
	return nil
}

func (_c *ConfirmationPresenceCreate) sqlSave(ctx context.Context) (*ConfirmationPresence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfirmationPresenceCreate) createSpec() (*ConfirmationPresence, *sqlgraph.CreateSpec) {
	var (
		_node = &ConfirmationPresence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(confirmationpresence.Table, sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Fullname(); ok {
		_spec.SetField(confirmationpresence.FieldFullname, field.TypeString, value)
		_node.Fullname = value
	}
	if value, ok := _c.mutation.PhotoBase64(); ok {
		_spec.SetField(confirmationpresence.FieldPhotoBase64, field.TypeString, value)
		_node.PhotoBase64 = value
	}
	if value, ok := _c.mutation.IsConfirmed(); ok {
		_spec.SetField(confirmationpresence.FieldIsConfirmed, field.TypeBool, value)
		_node.IsConfirmed = value
	}
	if nodes := _c.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmationpresence.FamilyTable,
			Columns: []string{confirmationpresence.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.family_presences = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConfirmationPresenceCreateBulk is the builder for creating many ConfirmationPresence entities in bulk.
type ConfirmationPresenceCreateBulk struct {
	config
	err      error
	builders []*ConfirmationPresenceCreate
}

// Save creates the ConfirmationPresence entities in the database.
func (_c *ConfirmationPresenceCreateBulk) Save(ctx context.Context) ([]*ConfirmationPresence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConfirmationPresence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfirmationPresenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfirmationPresenceCreateBulk) SaveX(ctx context.Context) []*ConfirmationPresence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfirmationPresenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfirmationPresenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
