// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/family"
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfirmationPresenceUpdate is the builder for updating ConfirmationPresence entities.
type ConfirmationPresenceUpdate struct {
	config
	hooks    []Hook
	mutation *ConfirmationPresenceMutation
}

// Where appends a list predicates to the ConfirmationPresenceUpdate builder.
func (_u *ConfirmationPresenceUpdate) Where(ps ...predicate.ConfirmationPresence) *ConfirmationPresenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFullname sets the "fullname" field.
func (_u *ConfirmationPresenceUpdate) SetFullname(v string) *ConfirmationPresenceUpdate {
	_u.mutation.SetFullname(v)
	return _u
}

// SetNillableFullname sets the "fullname" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdate) SetNillableFullname(v *string) *ConfirmationPresenceUpdate {
	if v != nil {
		_u.SetFullname(*v)
	}
	return _u
}

// SetPhotoBase64 sets the "photo_base64" field.
func (_u *ConfirmationPresenceUpdate) SetPhotoBase64(v string) *ConfirmationPresenceUpdate {
	_u.mutation.SetPhotoBase64(v)
	return _u
}

// SetNillablePhotoBase64 sets the "photo_base64" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdate) SetNillablePhotoBase64(v *string) *ConfirmationPresenceUpdate {
	if v != nil {
		_u.SetPhotoBase64(*v)
	}
	return _u
}

// ClearPhotoBase64 clears the value of the "photo_base64" field.
func (_u *ConfirmationPresenceUpdate) ClearPhotoBase64() *ConfirmationPresenceUpdate {
	_u.mutation.ClearPhotoBase64()
	return _u
}

// SetIsConfirmed sets the "is_confirmed" field.
func (_u *ConfirmationPresenceUpdate) SetIsConfirmed(v bool) *ConfirmationPresenceUpdate {
	_u.mutation.SetIsConfirmed(v)
	return _u
}

// SetNillableIsConfirmed sets the "is_confirmed" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdate) SetNillableIsConfirmed(v *bool) *ConfirmationPresenceUpdate {
	if v != nil {
		_u.SetIsConfirmed(*v)
	}
	return _u
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_u *ConfirmationPresenceUpdate) SetFamilyID(id int) *ConfirmationPresenceUpdate {
	_u.mutation.SetFamilyID(id)
	return _u
}

// SetNillableFamilyID sets the "family" edge to the Family entity by ID if the given value is not nil.
func (_u *ConfirmationPresenceUpdate) SetNillableFamilyID(id *int) *ConfirmationPresenceUpdate {
	if id != nil {
		_u = _u.SetFamilyID(*id)
	}
	return _u
}

// SetFamily sets the "family" edge to the Family entity.
func (_u *ConfirmationPresenceUpdate) SetFamily(v *Family) *ConfirmationPresenceUpdate {
	return _u.SetFamilyID(v.ID)
}

// Mutation returns the ConfirmationPresenceMutation object of the builder.
func (_u *ConfirmationPresenceUpdate) Mutation() *ConfirmationPresenceMutation {
	return _u.mutation
}

// ClearFamily clears the "family" edge to the Family entity.
func (_u *ConfirmationPresenceUpdate) ClearFamily() *ConfirmationPresenceUpdate {
	_u.mutation.ClearFamily()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfirmationPresenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfirmationPresenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfirmationPresenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfirmationPresenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConfirmationPresenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(confirmationpresence.Table, confirmationpresence.Columns, sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Fullname(); ok {
		_spec.SetField(confirmationpresence.FieldFullname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhotoBase64(); ok {
		_spec.SetField(confirmationpresence.FieldPhotoBase64, field.TypeString, value)
	}
	if _u.mutation.PhotoBase64Cleared() {
		_spec.ClearField(confirmationpresence.FieldPhotoBase64, field.TypeString)
	}
	if value, ok := _u.mutation.IsConfirmed(); ok {
		_spec.SetField(confirmationpresence.FieldIsConfirmed, field.TypeBool, value)
	}
	if _u.mutation.FamilyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmationpresence.FamilyTable,
			Columns: []string{confirmationpresence.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmationpresence.FamilyTable,
			Columns: []string{confirmationpresence.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{confirmationpresence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfirmationPresenceUpdateOne is the builder for updating a single ConfirmationPresence entity.
type ConfirmationPresenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfirmationPresenceMutation
}

// SetFullname sets the "fullname" field.
func (_u *ConfirmationPresenceUpdateOne) SetFullname(v string) *ConfirmationPresenceUpdateOne {
	_u.mutation.SetFullname(v)
	return _u
}

// SetNillableFullname sets the "fullname" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdateOne) SetNillableFullname(v *string) *ConfirmationPresenceUpdateOne {
	if v != nil {
		_u.SetFullname(*v)
	}
	return _u
}

// SetPhotoBase64 sets the "photo_base64" field.
func (_u *ConfirmationPresenceUpdateOne) SetPhotoBase64(v string) *ConfirmationPresenceUpdateOne {
	_u.mutation.SetPhotoBase64(v)
	return _u
}

// SetNillablePhotoBase64 sets the "photo_base64" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdateOne) SetNillablePhotoBase64(v *string) *ConfirmationPresenceUpdateOne {
	if v != nil {
		_u.SetPhotoBase64(*v)
	}
	return _u
}

// ClearPhotoBase64 clears the value of the "photo_base64" field.
func (_u *ConfirmationPresenceUpdateOne) ClearPhotoBase64() *ConfirmationPresenceUpdateOne {
	_u.mutation.ClearPhotoBase64()
	return _u
}

// SetIsConfirmed sets the "is_confirmed" field.
func (_u *ConfirmationPresenceUpdateOne) SetIsConfirmed(v bool) *ConfirmationPresenceUpdateOne {
	_u.mutation.SetIsConfirmed(v)
	return _u
}

// SetNillableIsConfirmed sets the "is_confirmed" field if the given value is not nil.
func (_u *ConfirmationPresenceUpdateOne) SetNillableIsConfirmed(v *bool) *ConfirmationPresenceUpdateOne {
	if v != nil {
		_u.SetIsConfirmed(*v)
	}
	return _u
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_u *ConfirmationPresenceUpdateOne) SetFamilyID(id int) *ConfirmationPresenceUpdateOne {
	_u.mutation.SetFamilyID(id)
	return _u
}

// SetNillableFamilyID sets the "family" edge to the Family entity by ID if the given value is not nil.
func (_u *ConfirmationPresenceUpdateOne) SetNillableFamilyID(id *int) *ConfirmationPresenceUpdateOne {
	if id != nil {
		_u = _u.SetFamilyID(*id)
	}
	return _u
}

// SetFamily sets the "family" edge to the Family entity.
func (_u *ConfirmationPresenceUpdateOne) SetFamily(v *Family) *ConfirmationPresenceUpdateOne {
	return _u.SetFamilyID(v.ID)
}

// Mutation returns the ConfirmationPresenceMutation object of the builder.
func (_u *ConfirmationPresenceUpdateOne) Mutation() *ConfirmationPresenceMutation {
	return _u.mutation
}

// ClearFamily clears the "family" edge to the Family entity.
func (_u *ConfirmationPresenceUpdateOne) ClearFamily() *ConfirmationPresenceUpdateOne {
	_u.mutation.ClearFamily()
	return _u
}

// Where appends a list predicates to the ConfirmationPresenceUpdate builder.
func (_u *ConfirmationPresenceUpdateOne) Where(ps ...predicate.ConfirmationPresence) *ConfirmationPresenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfirmationPresenceUpdateOne) Select(field string, fields ...string) *ConfirmationPresenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfirmationPresence entity.
func (_u *ConfirmationPresenceUpdateOne) Save(ctx context.Context) (*ConfirmationPresence, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfirmationPresenceUpdateOne) SaveX(ctx context.Context) *ConfirmationPresence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfirmationPresenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfirmationPresenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConfirmationPresenceUpdateOne) sqlSave(ctx context.Context) (_node *ConfirmationPresence, err error) {
	_spec := sqlgraph.NewUpdateSpec(confirmationpresence.Table, confirmationpresence.Columns, sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfirmationPresence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, confirmationpresence.FieldID)
		for _, f := range fields {
			if !confirmationpresence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != confirmationpresence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Fullname(); ok {
		_spec.SetField(confirmationpresence.FieldFullname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhotoBase64(); ok {
		_spec.SetField(confirmationpresence.FieldPhotoBase64, field.TypeString, value)
	}
	if _u.mutation.PhotoBase64Cleared() {
		_spec.ClearField(confirmationpresence.FieldPhotoBase64, field.TypeString)
	}
	if value, ok := _u.mutation.IsConfirmed(); ok {
		_spec.SetField(confirmationpresence.FieldIsConfirmed, field.TypeBool, value)
	}
	if _u.mutation.FamilyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmationpresence.FamilyTable,
			Columns: []string{confirmationpresence.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmationpresence.FamilyTable,
			Columns: []string{confirmationpresence.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConfirmationPresence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{confirmationpresence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
