// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfirmationPresenceDelete is the builder for deleting a ConfirmationPresence entity.
type ConfirmationPresenceDelete struct {
	config
	hooks    []Hook
	mutation *ConfirmationPresenceMutation
}

// Where appends a list predicates to the ConfirmationPresenceDelete builder.
func (_d *ConfirmationPresenceDelete) Where(ps ...predicate.ConfirmationPresence) *ConfirmationPresenceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ConfirmationPresenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConfirmationPresenceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ConfirmationPresenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(confirmationpresence.Table, sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ConfirmationPresenceDeleteOne is the builder for deleting a single ConfirmationPresence entity.
type ConfirmationPresenceDeleteOne struct {
	_d *ConfirmationPresenceDelete
}

// Where appends a list predicates to the ConfirmationPresenceDelete builder.
func (_d *ConfirmationPresenceDeleteOne) Where(ps ...predicate.ConfirmationPresence) *ConfirmationPresenceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ConfirmationPresenceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{confirmationpresence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConfirmationPresenceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
