// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/family"
	"wedding_api/ent/familyaccesstoken"
	"wedding_api/ent/predicate"
	"wedding_api/ent/session"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FamilyUpdate is the builder for updating Family entities.
type FamilyUpdate struct {
	config
	hooks    []Hook
	mutation *FamilyMutation
}

// Where appends a list predicates to the FamilyUpdate builder.
func (_u *FamilyUpdate) Where(ps ...predicate.Family) *FamilyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FamilyUpdate) SetName(v string) *FamilyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FamilyUpdate) SetNillableName(v *string) *FamilyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddPresenceIDs adds the "presences" edge to the ConfirmationPresence entity by IDs.
func (_u *FamilyUpdate) AddPresenceIDs(ids ...int) *FamilyUpdate {
	_u.mutation.AddPresenceIDs(ids...)
	return _u
}

// AddPresences adds the "presences" edges to the ConfirmationPresence entity.
func (_u *FamilyUpdate) AddPresences(v ...*ConfirmationPresence) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPresenceIDs(ids...)
}

// AddAccessTokenIDs adds the "access_tokens" edge to the FamilyAccessToken entity by IDs.
func (_u *FamilyUpdate) AddAccessTokenIDs(ids ...int) *FamilyUpdate {
	_u.mutation.AddAccessTokenIDs(ids...)
	return _u
}

// AddAccessTokens adds the "access_tokens" edges to the FamilyAccessToken entity.
func (_u *FamilyUpdate) AddAccessTokens(v ...*FamilyAccessToken) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccessTokenIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *FamilyUpdate) AddSessionIDs(ids ...int) *FamilyUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *FamilyUpdate) AddSessions(v ...*Session) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the FamilyMutation object of the builder.
func (_u *FamilyUpdate) Mutation() *FamilyMutation {
	return _u.mutation
}

// ClearPresences clears all "presences" edges to the ConfirmationPresence entity.
func (_u *FamilyUpdate) ClearPresences() *FamilyUpdate {
	_u.mutation.ClearPresences()
	return _u
}

// RemovePresenceIDs removes the "presences" edge to ConfirmationPresence entities by IDs.
func (_u *FamilyUpdate) RemovePresenceIDs(ids ...int) *FamilyUpdate {
	_u.mutation.RemovePresenceIDs(ids...)
	return _u
}

// RemovePresences removes "presences" edges to ConfirmationPresence entities.
func (_u *FamilyUpdate) RemovePresences(v ...*ConfirmationPresence) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePresenceIDs(ids...)
}

// ClearAccessTokens clears all "access_tokens" edges to the FamilyAccessToken entity.
func (_u *FamilyUpdate) ClearAccessTokens() *FamilyUpdate {
	_u.mutation.ClearAccessTokens()
	return _u
}

// RemoveAccessTokenIDs removes the "access_tokens" edge to FamilyAccessToken entities by IDs.
func (_u *FamilyUpdate) RemoveAccessTokenIDs(ids ...int) *FamilyUpdate {
	_u.mutation.RemoveAccessTokenIDs(ids...)
	return _u
}

// RemoveAccessTokens removes "access_tokens" edges to FamilyAccessToken entities.
func (_u *FamilyUpdate) RemoveAccessTokens(v ...*FamilyAccessToken) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccessTokenIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *FamilyUpdate) ClearSessions() *FamilyUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *FamilyUpdate) RemoveSessionIDs(ids ...int) *FamilyUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *FamilyUpdate) RemoveSessions(v ...*Session) *FamilyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FamilyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FamilyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FamilyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(family.Table, family.Columns, sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(family.FieldName, field.TypeString, value)
	}
	if _u.mutation.PresencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPresencesIDs(); len(nodes) > 0 && !_u.mutation.PresencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PresencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccessTokensIDs(); len(nodes) > 0 && !_u.mutation.AccessTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{family.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FamilyUpdateOne is the builder for updating a single Family entity.
type FamilyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FamilyMutation
}

// SetName sets the "name" field.
func (_u *FamilyUpdateOne) SetName(v string) *FamilyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FamilyUpdateOne) SetNillableName(v *string) *FamilyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddPresenceIDs adds the "presences" edge to the ConfirmationPresence entity by IDs.
func (_u *FamilyUpdateOne) AddPresenceIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.AddPresenceIDs(ids...)
	return _u
}

// AddPresences adds the "presences" edges to the ConfirmationPresence entity.
func (_u *FamilyUpdateOne) AddPresences(v ...*ConfirmationPresence) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPresenceIDs(ids...)
}

// AddAccessTokenIDs adds the "access_tokens" edge to the FamilyAccessToken entity by IDs.
func (_u *FamilyUpdateOne) AddAccessTokenIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.AddAccessTokenIDs(ids...)
	return _u
}

// AddAccessTokens adds the "access_tokens" edges to the FamilyAccessToken entity.
func (_u *FamilyUpdateOne) AddAccessTokens(v ...*FamilyAccessToken) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccessTokenIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *FamilyUpdateOne) AddSessionIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *FamilyUpdateOne) AddSessions(v ...*Session) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the FamilyMutation object of the builder.
func (_u *FamilyUpdateOne) Mutation() *FamilyMutation {
	return _u.mutation
}

// ClearPresences clears all "presences" edges to the ConfirmationPresence entity.
func (_u *FamilyUpdateOne) ClearPresences() *FamilyUpdateOne {
	_u.mutation.ClearPresences()
	return _u
}

// RemovePresenceIDs removes the "presences" edge to ConfirmationPresence entities by IDs.
func (_u *FamilyUpdateOne) RemovePresenceIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.RemovePresenceIDs(ids...)
	return _u
}

// RemovePresences removes "presences" edges to ConfirmationPresence entities.
func (_u *FamilyUpdateOne) RemovePresences(v ...*ConfirmationPresence) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePresenceIDs(ids...)
}

// ClearAccessTokens clears all "access_tokens" edges to the FamilyAccessToken entity.
func (_u *FamilyUpdateOne) ClearAccessTokens() *FamilyUpdateOne {
	_u.mutation.ClearAccessTokens()
	return _u
}

// RemoveAccessTokenIDs removes the "access_tokens" edge to FamilyAccessToken entities by IDs.
func (_u *FamilyUpdateOne) RemoveAccessTokenIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.RemoveAccessTokenIDs(ids...)
	return _u
}

// RemoveAccessTokens removes "access_tokens" edges to FamilyAccessToken entities.
func (_u *FamilyUpdateOne) RemoveAccessTokens(v ...*FamilyAccessToken) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccessTokenIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *FamilyUpdateOne) ClearSessions() *FamilyUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *FamilyUpdateOne) RemoveSessionIDs(ids ...int) *FamilyUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *FamilyUpdateOne) RemoveSessions(v ...*Session) *FamilyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the FamilyUpdate builder.
func (_u *FamilyUpdateOne) Where(ps ...predicate.Family) *FamilyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FamilyUpdateOne) Select(field string, fields ...string) *FamilyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Family entity.
func (_u *FamilyUpdateOne) Save(ctx context.Context) (*Family, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilyUpdateOne) SaveX(ctx context.Context) *Family {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FamilyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FamilyUpdateOne) sqlSave(ctx context.Context) (_node *Family, err error) {
	_spec := sqlgraph.NewUpdateSpec(family.Table, family.Columns, sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Family.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, family.FieldID)
		for _, f := range fields {
			if !family.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != family.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(family.FieldName, field.TypeString, value)
	}
	if _u.mutation.PresencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPresencesIDs(); len(nodes) > 0 && !_u.mutation.PresencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PresencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.PresencesTable,
			Columns: []string{family.PresencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confirmationpresence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccessTokensIDs(); len(nodes) > 0 && !_u.mutation.AccessTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.AccessTokensTable,
			Columns: []string{family.AccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SessionsTable,
			Columns: []string{family.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Family{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{family.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
