// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"wedding_api/ent/family"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Family is the model entity for the Family schema.
type Family struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FamilyQuery when eager-loading is set.
	Edges        FamilyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FamilyEdges holds the relations/edges for other nodes in the graph.
type FamilyEdges struct {
	// Presences holds the value of the presences edge.
	Presences []*ConfirmationPresence `json:"presences,omitempty"`
	// AccessTokens holds the value of the access_tokens edge.
	AccessTokens []*FamilyAccessToken `json:"access_tokens,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PresencesOrErr returns the Presences value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) PresencesOrErr() ([]*ConfirmationPresence, error) {
	if e.loadedTypes[0] {
		return e.Presences, nil
	}
	return nil, &NotLoadedError{edge: "presences"}
}

// AccessTokensOrErr returns the AccessTokens value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) AccessTokensOrErr() ([]*FamilyAccessToken, error) {
	if e.loadedTypes[1] {
		return e.AccessTokens, nil
	}
	return nil, &NotLoadedError{edge: "access_tokens"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[2] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Family) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case family.FieldID:
			values[i] = new(sql.NullInt64)
		case family.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Family fields.
func (_m *Family) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case family.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case family.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Family.
// This includes values selected through modifiers, order, etc.
func (_m *Family) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPresences queries the "presences" edge of the Family entity.
func (_m *Family) QueryPresences() *ConfirmationPresenceQuery {
	return NewFamilyClient(_m.config).QueryPresences(_m)
}

// QueryAccessTokens queries the "access_tokens" edge of the Family entity.
func (_m *Family) QueryAccessTokens() *FamilyAccessTokenQuery {
	return NewFamilyClient(_m.config).QueryAccessTokens(_m)
}

// QuerySessions queries the "sessions" edge of the Family entity.
func (_m *Family) QuerySessions() *SessionQuery {
	return NewFamilyClient(_m.config).QuerySessions(_m)
}

// Update returns a builder for updating this Family.
// Note that you need to call Family.Unwrap() before calling this method if this Family
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Family) Update() *FamilyUpdateOne {
	return NewFamilyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Family entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Family) Unwrap() *Family {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Family is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Family) String() string {
	var builder strings.Builder
	builder.WriteString("Family(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Families is a parsable slice of Family.
type Families []*Family
