// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wedding_api/ent/family"
	"wedding_api/ent/familyaccesstoken"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FamilyAccessToken is the model entity for the FamilyAccessToken schema.
type FamilyAccessToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FamilyAccessTokenQuery when eager-loading is set.
	Edges                FamilyAccessTokenEdges `json:"edges"`
	family_access_tokens *int
	selectValues         sql.SelectValues
}

// FamilyAccessTokenEdges holds the relations/edges for other nodes in the graph.
type FamilyAccessTokenEdges struct {
	// Family holds the value of the family edge.
	Family *Family `json:"family,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FamilyOrErr returns the Family value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FamilyAccessTokenEdges) FamilyOrErr() (*Family, error) {
	if e.Family != nil {
		return e.Family, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: family.Label}
	}
	return nil, &NotLoadedError{edge: "family"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FamilyAccessToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case familyaccesstoken.FieldID:
			values[i] = new(sql.NullInt64)
		case familyaccesstoken.FieldTokenHash:
			values[i] = new(sql.NullString)
		case familyaccesstoken.FieldExpiresAt, familyaccesstoken.FieldRevokedAt, familyaccesstoken.FieldLastUsedAt, familyaccesstoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case familyaccesstoken.ForeignKeys[0]: // family_access_tokens
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FamilyAccessToken fields.
func (_m *FamilyAccessToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case familyaccesstoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case familyaccesstoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case familyaccesstoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case familyaccesstoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case familyaccesstoken.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case familyaccesstoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case familyaccesstoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field family_access_tokens", value)
			} else if value.Valid {
				_m.family_access_tokens = new(int)
				*_m.family_access_tokens = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FamilyAccessToken.
// This includes values selected through modifiers, order, etc.
func (_m *FamilyAccessToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFamily queries the "family" edge of the FamilyAccessToken entity.
func (_m *FamilyAccessToken) QueryFamily() *FamilyQuery {
	return NewFamilyAccessTokenClient(_m.config).QueryFamily(_m)
}

// Update returns a builder for updating this FamilyAccessToken.
// Note that you need to call FamilyAccessToken.Unwrap() before calling this method if this FamilyAccessToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FamilyAccessToken) Update() *FamilyAccessTokenUpdateOne {
	return NewFamilyAccessTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FamilyAccessToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FamilyAccessToken) Unwrap() *FamilyAccessToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FamilyAccessToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FamilyAccessToken) String() string {
	var builder strings.Builder
	builder.WriteString("FamilyAccessToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FamilyAccessTokens is a parsable slice of FamilyAccessToken.
type FamilyAccessTokens []*FamilyAccessToken
