// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wedding_api/ent/family"
	"wedding_api/ent/familyaccesstoken"
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FamilyAccessTokenUpdate is the builder for updating FamilyAccessToken entities.
type FamilyAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *FamilyAccessTokenMutation
}

// Where appends a list predicates to the FamilyAccessTokenUpdate builder.
func (_u *FamilyAccessTokenUpdate) Where(ps ...predicate.FamilyAccessToken) *FamilyAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *FamilyAccessTokenUpdate) SetTokenHash(v string) *FamilyAccessTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdate) SetNillableTokenHash(v *string) *FamilyAccessTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FamilyAccessTokenUpdate) SetExpiresAt(v time.Time) *FamilyAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *FamilyAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *FamilyAccessTokenUpdate) ClearExpiresAt() *FamilyAccessTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *FamilyAccessTokenUpdate) SetRevokedAt(v time.Time) *FamilyAccessTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdate) SetNillableRevokedAt(v *time.Time) *FamilyAccessTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *FamilyAccessTokenUpdate) ClearRevokedAt() *FamilyAccessTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *FamilyAccessTokenUpdate) SetLastUsedAt(v time.Time) *FamilyAccessTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdate) SetNillableLastUsedAt(v *time.Time) *FamilyAccessTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *FamilyAccessTokenUpdate) ClearLastUsedAt() *FamilyAccessTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FamilyAccessTokenUpdate) SetCreatedAt(v time.Time) *FamilyAccessTokenUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdate) SetNillableCreatedAt(v *time.Time) *FamilyAccessTokenUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_u *FamilyAccessTokenUpdate) SetFamilyID(id int) *FamilyAccessTokenUpdate {
	_u.mutation.SetFamilyID(id)
	return _u
}

// SetFamily sets the "family" edge to the Family entity.
func (_u *FamilyAccessTokenUpdate) SetFamily(v *Family) *FamilyAccessTokenUpdate {
	return _u.SetFamilyID(v.ID)
}

// Mutation returns the FamilyAccessTokenMutation object of the builder.
func (_u *FamilyAccessTokenUpdate) Mutation() *FamilyAccessTokenMutation {
	return _u.mutation
}

// ClearFamily clears the "family" edge to the Family entity.
func (_u *FamilyAccessTokenUpdate) ClearFamily() *FamilyAccessTokenUpdate {
	_u.mutation.ClearFamily()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FamilyAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilyAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FamilyAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilyAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FamilyAccessTokenUpdate) check() error {
	if _u.mutation.FamilyCleared() && len(_u.mutation.FamilyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FamilyAccessToken.family"`)
	}
	return nil
}

func (_u *FamilyAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(familyaccesstoken.Table, familyaccesstoken.Columns, sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(familyaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(familyaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.FamilyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   familyaccesstoken.FamilyTable,
			Columns: []string{familyaccesstoken.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   familyaccesstoken.FamilyTable,
			Columns: []string{familyaccesstoken.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{familyaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FamilyAccessTokenUpdateOne is the builder for updating a single FamilyAccessToken entity.
type FamilyAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FamilyAccessTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *FamilyAccessTokenUpdateOne) SetTokenHash(v string) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdateOne) SetNillableTokenHash(v *string) *FamilyAccessTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FamilyAccessTokenUpdateOne) SetExpiresAt(v time.Time) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *FamilyAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *FamilyAccessTokenUpdateOne) ClearExpiresAt() *FamilyAccessTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *FamilyAccessTokenUpdateOne) SetRevokedAt(v time.Time) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *FamilyAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *FamilyAccessTokenUpdateOne) ClearRevokedAt() *FamilyAccessTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *FamilyAccessTokenUpdateOne) SetLastUsedAt(v time.Time) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *FamilyAccessTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *FamilyAccessTokenUpdateOne) ClearLastUsedAt() *FamilyAccessTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FamilyAccessTokenUpdateOne) SetCreatedAt(v time.Time) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FamilyAccessTokenUpdateOne) SetNillableCreatedAt(v *time.Time) *FamilyAccessTokenUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_u *FamilyAccessTokenUpdateOne) SetFamilyID(id int) *FamilyAccessTokenUpdateOne {
	_u.mutation.SetFamilyID(id)
	return _u
}

// SetFamily sets the "family" edge to the Family entity.
func (_u *FamilyAccessTokenUpdateOne) SetFamily(v *Family) *FamilyAccessTokenUpdateOne {
	return _u.SetFamilyID(v.ID)
}

// Mutation returns the FamilyAccessTokenMutation object of the builder.
func (_u *FamilyAccessTokenUpdateOne) Mutation() *FamilyAccessTokenMutation {
	return _u.mutation
}

// ClearFamily clears the "family" edge to the Family entity.
func (_u *FamilyAccessTokenUpdateOne) ClearFamily() *FamilyAccessTokenUpdateOne {
	_u.mutation.ClearFamily()
	return _u
}

// Where appends a list predicates to the FamilyAccessTokenUpdate builder.
func (_u *FamilyAccessTokenUpdateOne) Where(ps ...predicate.FamilyAccessToken) *FamilyAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FamilyAccessTokenUpdateOne) Select(field string, fields ...string) *FamilyAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FamilyAccessToken entity.
func (_u *FamilyAccessTokenUpdateOne) Save(ctx context.Context) (*FamilyAccessToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilyAccessTokenUpdateOne) SaveX(ctx context.Context) *FamilyAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FamilyAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilyAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FamilyAccessTokenUpdateOne) check() error {
	if _u.mutation.FamilyCleared() && len(_u.mutation.FamilyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FamilyAccessToken.family"`)
	}
	return nil
}

func (_u *FamilyAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *FamilyAccessToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(familyaccesstoken.Table, familyaccesstoken.Columns, sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FamilyAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, familyaccesstoken.FieldID)
		for _, f := range fields {
			if !familyaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != familyaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(familyaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(familyaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(familyaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.FamilyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   familyaccesstoken.FamilyTable,
			Columns: []string{familyaccesstoken.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   familyaccesstoken.FamilyTable,
			Columns: []string{familyaccesstoken.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FamilyAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{familyaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
