// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/family"
	"wedding_api/ent/familyaccesstoken"
	"wedding_api/ent/predicate"
	"wedding_api/ent/session"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FamilyQuery is the builder for querying Family entities.
type FamilyQuery struct {
	config
	ctx              *QueryContext
	order            []family.OrderOption
	inters           []Interceptor
	predicates       []predicate.Family
	withPresences    *ConfirmationPresenceQuery
	withAccessTokens *FamilyAccessTokenQuery
	withSessions     *SessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FamilyQuery builder.
func (_q *FamilyQuery) Where(ps ...predicate.Family) *FamilyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FamilyQuery) Limit(limit int) *FamilyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FamilyQuery) Offset(offset int) *FamilyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FamilyQuery) Unique(unique bool) *FamilyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FamilyQuery) Order(o ...family.OrderOption) *FamilyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPresences chains the current query on the "presences" edge.
func (_q *FamilyQuery) QueryPresences() *ConfirmationPresenceQuery {
	query := (&ConfirmationPresenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(family.Table, family.FieldID, selector),
			sqlgraph.To(confirmationpresence.Table, confirmationpresence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, family.PresencesTable, family.PresencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccessTokens chains the current query on the "access_tokens" edge.
func (_q *FamilyQuery) QueryAccessTokens() *FamilyAccessTokenQuery {
	query := (&FamilyAccessTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(family.Table, family.FieldID, selector),
			sqlgraph.To(familyaccesstoken.Table, familyaccesstoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, family.AccessTokensTable, family.AccessTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySessions chains the current query on the "sessions" edge.
func (_q *FamilyQuery) QuerySessions() *SessionQuery {
	query := (&SessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(family.Table, family.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, family.SessionsTable, family.SessionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Family entity from the query.
// Returns a *NotFoundError when no Family was found.
func (_q *FamilyQuery) First(ctx context.Context) (*Family, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{family.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FamilyQuery) FirstX(ctx context.Context) *Family {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Family ID from the query.
// Returns a *NotFoundError when no Family ID was found.
func (_q *FamilyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{family.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FamilyQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Family entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Family entity is found.
// Returns a *NotFoundError when no Family entities are found.
func (_q *FamilyQuery) Only(ctx context.Context) (*Family, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{family.Label}
	default:
		return nil, &NotSingularError{family.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FamilyQuery) OnlyX(ctx context.Context) *Family {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Family ID in the query.
// Returns a *NotSingularError when more than one Family ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FamilyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{family.Label}
	default:
		err = &NotSingularError{family.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FamilyQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Families.
func (_q *FamilyQuery) All(ctx context.Context) ([]*Family, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Family, *FamilyQuery]()
	return withInterceptors[[]*Family](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FamilyQuery) AllX(ctx context.Context) []*Family {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Family IDs.
func (_q *FamilyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(family.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FamilyQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FamilyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FamilyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FamilyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FamilyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FamilyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FamilyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FamilyQuery) Clone() *FamilyQuery {
	if _q == nil {
		return nil
	}
	return &FamilyQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]family.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Family{}, _q.predicates...),
		withPresences:    _q.withPresences.Clone(),
		withAccessTokens: _q.withAccessTokens.Clone(),
		withSessions:     _q.withSessions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPresences tells the query-builder to eager-load the nodes that are connected to
// the "presences" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FamilyQuery) WithPresences(opts ...func(*ConfirmationPresenceQuery)) *FamilyQuery {
	query := (&ConfirmationPresenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPresences = query
	return _q
}

// WithAccessTokens tells the query-builder to eager-load the nodes that are connected to
// the "access_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FamilyQuery) WithAccessTokens(opts ...func(*FamilyAccessTokenQuery)) *FamilyQuery {
	query := (&FamilyAccessTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccessTokens = query
	return _q
}

// WithSessions tells the query-builder to eager-load the nodes that are connected to
// the "sessions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FamilyQuery) WithSessions(opts ...func(*SessionQuery)) *FamilyQuery {
	query := (&SessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Family.Query().
//		GroupBy(family.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FamilyQuery) GroupBy(field string, fields ...string) *FamilyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FamilyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = family.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Family.Query().
//		Select(family.FieldName).
//		Scan(ctx, &v)
func (_q *FamilyQuery) Select(fields ...string) *FamilySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FamilySelect{FamilyQuery: _q}
	sbuild.label = family.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FamilySelect configured with the given aggregations.
func (_q *FamilyQuery) Aggregate(fns ...AggregateFunc) *FamilySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FamilyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !family.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FamilyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Family, error) {
	var (
		nodes       = []*Family{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPresences != nil,
			_q.withAccessTokens != nil,
			_q.withSessions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Family).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Family{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPresences; query != nil {
		if err := _q.loadPresences(ctx, query, nodes,
			func(n *Family) { n.Edges.Presences = []*ConfirmationPresence{} },
			func(n *Family, e *ConfirmationPresence) { n.Edges.Presences = append(n.Edges.Presences, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAccessTokens; query != nil {
		if err := _q.loadAccessTokens(ctx, query, nodes,
			func(n *Family) { n.Edges.AccessTokens = []*FamilyAccessToken{} },
			func(n *Family, e *FamilyAccessToken) { n.Edges.AccessTokens = append(n.Edges.AccessTokens, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSessions; query != nil {
		if err := _q.loadSessions(ctx, query, nodes,
			func(n *Family) { n.Edges.Sessions = []*Session{} },
			func(n *Family, e *Session) { n.Edges.Sessions = append(n.Edges.Sessions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FamilyQuery) loadPresences(ctx context.Context, query *ConfirmationPresenceQuery, nodes []*Family, init func(*Family), assign func(*Family, *ConfirmationPresence)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Family)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ConfirmationPresence(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(family.PresencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.family_presences
		if fk == nil {
			return fmt.Errorf(`foreign-key "family_presences" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "family_presences" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FamilyQuery) loadAccessTokens(ctx context.Context, query *FamilyAccessTokenQuery, nodes []*Family, init func(*Family), assign func(*Family, *FamilyAccessToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Family)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FamilyAccessToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(family.AccessTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.family_access_tokens
		if fk == nil {
			return fmt.Errorf(`foreign-key "family_access_tokens" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "family_access_tokens" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FamilyQuery) loadSessions(ctx context.Context, query *SessionQuery, nodes []*Family, init func(*Family), assign func(*Family, *Session)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Family)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Session(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(family.SessionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.family_sessions
		if fk == nil {
			return fmt.Errorf(`foreign-key "family_sessions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "family_sessions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *FamilyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FamilyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(family.Table, family.Columns, sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, family.FieldID)
		for i := range fields {
			if fields[i] != family.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FamilyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(family.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = family.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FamilyGroupBy is the group-by builder for Family entities.
type FamilyGroupBy struct {
	selector
	build *FamilyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FamilyGroupBy) Aggregate(fns ...AggregateFunc) *FamilyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FamilyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FamilyQuery, *FamilyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FamilyGroupBy) sqlScan(ctx context.Context, root *FamilyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FamilySelect is the builder for selecting fields of Family entities.
type FamilySelect struct {
	*FamilyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FamilySelect) Aggregate(fns ...AggregateFunc) *FamilySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FamilySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FamilyQuery, *FamilySelect](ctx, _s.FamilyQuery, _s, _s.inters, v)
}

func (_s *FamilySelect) sqlScan(ctx context.Context, root *FamilyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
