// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wedding_api/ent/familyaccesstoken"
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FamilyAccessTokenDelete is the builder for deleting a FamilyAccessToken entity.
type FamilyAccessTokenDelete struct {
	config
	hooks    []Hook
	mutation *FamilyAccessTokenMutation
}

// Where appends a list predicates to the FamilyAccessTokenDelete builder.
func (_d *FamilyAccessTokenDelete) Where(ps ...predicate.FamilyAccessToken) *FamilyAccessTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FamilyAccessTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FamilyAccessTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FamilyAccessTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(familyaccesstoken.Table, sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FamilyAccessTokenDeleteOne is the builder for deleting a single FamilyAccessToken entity.
type FamilyAccessTokenDeleteOne struct {
	_d *FamilyAccessTokenDelete
}

// Where appends a list predicates to the FamilyAccessTokenDelete builder.
func (_d *FamilyAccessTokenDeleteOne) Where(ps ...predicate.FamilyAccessToken) *FamilyAccessTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FamilyAccessTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{familyaccesstoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FamilyAccessTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
