// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wedding_api/ent/family"
	"wedding_api/ent/familyaccesstoken"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FamilyAccessTokenCreate is the builder for creating a FamilyAccessToken entity.
type FamilyAccessTokenCreate struct {
	config
	mutation *FamilyAccessTokenMutation
	hooks    []Hook
}

// SetTokenHash sets the "token_hash" field.
func (_c *FamilyAccessTokenCreate) SetTokenHash(v string) *FamilyAccessTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *FamilyAccessTokenCreate) SetExpiresAt(v time.Time) *FamilyAccessTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *FamilyAccessTokenCreate) SetNillableExpiresAt(v *time.Time) *FamilyAccessTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *FamilyAccessTokenCreate) SetRevokedAt(v time.Time) *FamilyAccessTokenCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *FamilyAccessTokenCreate) SetNillableRevokedAt(v *time.Time) *FamilyAccessTokenCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *FamilyAccessTokenCreate) SetLastUsedAt(v time.Time) *FamilyAccessTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *FamilyAccessTokenCreate) SetNillableLastUsedAt(v *time.Time) *FamilyAccessTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FamilyAccessTokenCreate) SetCreatedAt(v time.Time) *FamilyAccessTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FamilyAccessTokenCreate) SetNillableCreatedAt(v *time.Time) *FamilyAccessTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetFamilyID sets the "family" edge to the Family entity by ID.
func (_c *FamilyAccessTokenCreate) SetFamilyID(id int) *FamilyAccessTokenCreate {
	_c.mutation.SetFamilyID(id)
	return _c
}

// SetFamily sets the "family" edge to the Family entity.
func (_c *FamilyAccessTokenCreate) SetFamily(v *Family) *FamilyAccessTokenCreate {
	return _c.SetFamilyID(v.ID)
}

// Mutation returns the FamilyAccessTokenMutation object of the builder.
func (_c *FamilyAccessTokenCreate) Mutation() *FamilyAccessTokenMutation {
	return _c.mutation
}

// Save creates the FamilyAccessToken in the database.
func (_c *FamilyAccessTokenCreate) Save(ctx context.Context) (*FamilyAccessToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FamilyAccessTokenCreate) SaveX(ctx context.Context) *FamilyAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FamilyAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FamilyAccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FamilyAccessTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := familyaccesstoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FamilyAccessTokenCreate) check() error {
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "FamilyAccessToken.token_hash"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FamilyAccessToken.created_at"`)}
	}
	if len(_c.mutation.FamilyIDs()) == 0 {
		return &ValidationError{Name: "family", err: errors.New(`ent: missing required edge "FamilyAccessToken.family"`)}
	}
	return nil
}

func (_c *FamilyAccessTokenCreate) sqlSave(ctx context.Context) (*FamilyAccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FamilyAccessTokenCreate) createSpec() (*FamilyAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &FamilyAccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(familyaccesstoken.Table, sqlgraph.NewFieldSpec(familyaccesstoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(familyaccesstoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(familyaccesstoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(familyaccesstoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.FamilyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   familyaccesstoken.FamilyTable,
			Columns: []string{familyaccesstoken.FamilyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.family_access_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FamilyAccessTokenCreateBulk is the builder for creating many FamilyAccessToken entities in bulk.
type FamilyAccessTokenCreateBulk struct {
	config
	err      error
	builders []*FamilyAccessTokenCreate
}

// Save creates the FamilyAccessToken entities in the database.
func (_c *FamilyAccessTokenCreateBulk) Save(ctx context.Context) ([]*FamilyAccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FamilyAccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FamilyAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FamilyAccessTokenCreateBulk) SaveX(ctx context.Context) []*FamilyAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FamilyAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FamilyAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
