// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/predicate"
	"wedding_api/ent/product"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeConfirmationPresence = "ConfirmationPresence"
	TypeProduct              = "Product"
)

// ConfirmationPresenceMutation represents an operation that mutates the ConfirmationPresence nodes in the graph.
type ConfirmationPresenceMutation struct {
	config
	op            Op
	typ           string
	id            *int
	fullname      *string
	photo_base64  *string
	is_confirmed  *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ConfirmationPresence, error)
	predicates    []predicate.ConfirmationPresence
}

var _ ent.Mutation = (*ConfirmationPresenceMutation)(nil)

// confirmationpresenceOption allows management of the mutation configuration using functional options.
type confirmationpresenceOption func(*ConfirmationPresenceMutation)

// newConfirmationPresenceMutation creates new mutation for the ConfirmationPresence entity.
func newConfirmationPresenceMutation(c config, op Op, opts ...confirmationpresenceOption) *ConfirmationPresenceMutation {
	m := &ConfirmationPresenceMutation{
		config:        c,
		op:            op,
		typ:           TypeConfirmationPresence,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withConfirmationPresenceID sets the ID field of the mutation.
func withConfirmationPresenceID(id int) confirmationpresenceOption {
	return func(m *ConfirmationPresenceMutation) {
		var (
			err   error
			once  sync.Once
			value *ConfirmationPresence
		)
		m.oldValue = func(ctx context.Context) (*ConfirmationPresence, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ConfirmationPresence.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withConfirmationPresence sets the old ConfirmationPresence of the mutation.
func withConfirmationPresence(node *ConfirmationPresence) confirmationpresenceOption {
	return func(m *ConfirmationPresenceMutation) {
		m.oldValue = func(context.Context) (*ConfirmationPresence, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ConfirmationPresenceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ConfirmationPresenceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ConfirmationPresenceMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ConfirmationPresenceMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ConfirmationPresence.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetFullname sets the "fullname" field.
func (m *ConfirmationPresenceMutation) SetFullname(s string) {
	m.fullname = &s
}

// Fullname returns the value of the "fullname" field in the mutation.
func (m *ConfirmationPresenceMutation) Fullname() (r string, exists bool) {
	v := m.fullname
	if v == nil {
		return
	}
	return *v, true
}

// OldFullname returns the old "fullname" field's value of the ConfirmationPresence entity.
// If the ConfirmationPresence object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConfirmationPresenceMutation) OldFullname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFullname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFullname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFullname: %w", err)
	}
	return oldValue.Fullname, nil
}

// ResetFullname resets all changes to the "fullname" field.
func (m *ConfirmationPresenceMutation) ResetFullname() {
	m.fullname = nil
}

// SetPhotoBase64 sets the "photo_base64" field.
func (m *ConfirmationPresenceMutation) SetPhotoBase64(s string) {
	m.photo_base64 = &s
}

// PhotoBase64 returns the value of the "photo_base64" field in the mutation.
func (m *ConfirmationPresenceMutation) PhotoBase64() (r string, exists bool) {
	v := m.photo_base64
	if v == nil {
		return
	}
	return *v, true
}

// OldPhotoBase64 returns the old "photo_base64" field's value of the ConfirmationPresence entity.
// If the ConfirmationPresence object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConfirmationPresenceMutation) OldPhotoBase64(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhotoBase64 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhotoBase64 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhotoBase64: %w", err)
	}
	return oldValue.PhotoBase64, nil
}

// ClearPhotoBase64 clears the value of the "photo_base64" field.
func (m *ConfirmationPresenceMutation) ClearPhotoBase64() {
	m.photo_base64 = nil
	m.clearedFields[confirmationpresence.FieldPhotoBase64] = struct{}{}
}

// PhotoBase64Cleared returns if the "photo_base64" field was cleared in this mutation.
func (m *ConfirmationPresenceMutation) PhotoBase64Cleared() bool {
	_, ok := m.clearedFields[confirmationpresence.FieldPhotoBase64]
	return ok
}

// ResetPhotoBase64 resets all changes to the "photo_base64" field.
func (m *ConfirmationPresenceMutation) ResetPhotoBase64() {
	m.photo_base64 = nil
	delete(m.clearedFields, confirmationpresence.FieldPhotoBase64)
}

// SetIsConfirmed sets the "is_confirmed" field.
func (m *ConfirmationPresenceMutation) SetIsConfirmed(b bool) {
	m.is_confirmed = &b
}

// IsConfirmed returns the value of the "is_confirmed" field in the mutation.
func (m *ConfirmationPresenceMutation) IsConfirmed() (r bool, exists bool) {
	v := m.is_confirmed
	if v == nil {
		return
	}
	return *v, true
}

// OldIsConfirmed returns the old "is_confirmed" field's value of the ConfirmationPresence entity.
// If the ConfirmationPresence object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConfirmationPresenceMutation) OldIsConfirmed(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsConfirmed is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsConfirmed requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsConfirmed: %w", err)
	}
	return oldValue.IsConfirmed, nil
}

// ResetIsConfirmed resets all changes to the "is_confirmed" field.
func (m *ConfirmationPresenceMutation) ResetIsConfirmed() {
	m.is_confirmed = nil
}

// Where appends a list predicates to the ConfirmationPresenceMutation builder.
func (m *ConfirmationPresenceMutation) Where(ps ...predicate.ConfirmationPresence) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ConfirmationPresenceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ConfirmationPresenceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ConfirmationPresence, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ConfirmationPresenceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ConfirmationPresenceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ConfirmationPresence).
func (m *ConfirmationPresenceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ConfirmationPresenceMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.fullname != nil {
		fields = append(fields, confirmationpresence.FieldFullname)
	}
	if m.photo_base64 != nil {
		fields = append(fields, confirmationpresence.FieldPhotoBase64)
	}
	if m.is_confirmed != nil {
		fields = append(fields, confirmationpresence.FieldIsConfirmed)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ConfirmationPresenceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case confirmationpresence.FieldFullname:
		return m.Fullname()
	case confirmationpresence.FieldPhotoBase64:
		return m.PhotoBase64()
	case confirmationpresence.FieldIsConfirmed:
		return m.IsConfirmed()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ConfirmationPresenceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case confirmationpresence.FieldFullname:
		return m.OldFullname(ctx)
	case confirmationpresence.FieldPhotoBase64:
		return m.OldPhotoBase64(ctx)
	case confirmationpresence.FieldIsConfirmed:
		return m.OldIsConfirmed(ctx)
	}
	return nil, fmt.Errorf("unknown ConfirmationPresence field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConfirmationPresenceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case confirmationpresence.FieldFullname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFullname(v)
		return nil
	case confirmationpresence.FieldPhotoBase64:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhotoBase64(v)
		return nil
	case confirmationpresence.FieldIsConfirmed:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsConfirmed(v)
		return nil
	}
	return fmt.Errorf("unknown ConfirmationPresence field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ConfirmationPresenceMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ConfirmationPresenceMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConfirmationPresenceMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ConfirmationPresence numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ConfirmationPresenceMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(confirmationpresence.FieldPhotoBase64) {
		fields = append(fields, confirmationpresence.FieldPhotoBase64)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ConfirmationPresenceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ConfirmationPresenceMutation) ClearField(name string) error {
	switch name {
	case confirmationpresence.FieldPhotoBase64:
		m.ClearPhotoBase64()
		return nil
	}
	return fmt.Errorf("unknown ConfirmationPresence nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ConfirmationPresenceMutation) ResetField(name string) error {
	switch name {
	case confirmationpresence.FieldFullname:
		m.ResetFullname()
		return nil
	case confirmationpresence.FieldPhotoBase64:
		m.ResetPhotoBase64()
		return nil
	case confirmationpresence.FieldIsConfirmed:
		m.ResetIsConfirmed()
		return nil
	}
	return fmt.Errorf("unknown ConfirmationPresence field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ConfirmationPresenceMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ConfirmationPresenceMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ConfirmationPresenceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ConfirmationPresenceMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ConfirmationPresenceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ConfirmationPresenceMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ConfirmationPresenceMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ConfirmationPresence unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ConfirmationPresenceMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ConfirmationPresence edge %s", name)
}

// ProductMutation represents an operation that mutates the Product nodes in the graph.
type ProductMutation struct {
	config
	op            Op
	typ           string
	id            *int
	title         *string
	reserved_by   *string
	image         *string
	value         *float64
	addvalue      *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Product, error)
	predicates    []predicate.Product
}

var _ ent.Mutation = (*ProductMutation)(nil)

// productOption allows management of the mutation configuration using functional options.
type productOption func(*ProductMutation)

// newProductMutation creates new mutation for the Product entity.
func newProductMutation(c config, op Op, opts ...productOption) *ProductMutation {
	m := &ProductMutation{
		config:        c,
		op:            op,
		typ:           TypeProduct,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProductID sets the ID field of the mutation.
func withProductID(id int) productOption {
	return func(m *ProductMutation) {
		var (
			err   error
			once  sync.Once
			value *Product
		)
		m.oldValue = func(ctx context.Context) (*Product, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Product.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProduct sets the old Product of the mutation.
func withProduct(node *Product) productOption {
	return func(m *ProductMutation) {
		m.oldValue = func(context.Context) (*Product, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProductMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProductMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProductMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProductMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Product.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *ProductMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ProductMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ProductMutation) ResetTitle() {
	m.title = nil
}

// SetReservedBy sets the "reserved_by" field.
func (m *ProductMutation) SetReservedBy(s string) {
	m.reserved_by = &s
}

// ReservedBy returns the value of the "reserved_by" field in the mutation.
func (m *ProductMutation) ReservedBy() (r string, exists bool) {
	v := m.reserved_by
	if v == nil {
		return
	}
	return *v, true
}

// OldReservedBy returns the old "reserved_by" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldReservedBy(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReservedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReservedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReservedBy: %w", err)
	}
	return oldValue.ReservedBy, nil
}

// ResetReservedBy resets all changes to the "reserved_by" field.
func (m *ProductMutation) ResetReservedBy() {
	m.reserved_by = nil
}

// SetImage sets the "image" field.
func (m *ProductMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *ProductMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ClearImage clears the value of the "image" field.
func (m *ProductMutation) ClearImage() {
	m.image = nil
	m.clearedFields[product.FieldImage] = struct{}{}
}

// ImageCleared returns if the "image" field was cleared in this mutation.
func (m *ProductMutation) ImageCleared() bool {
	_, ok := m.clearedFields[product.FieldImage]
	return ok
}

// ResetImage resets all changes to the "image" field.
func (m *ProductMutation) ResetImage() {
	m.image = nil
	delete(m.clearedFields, product.FieldImage)
}

// SetValue sets the "value" field.
func (m *ProductMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *ProductMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *ProductMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *ProductMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *ProductMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// Where appends a list predicates to the ProductMutation builder.
func (m *ProductMutation) Where(ps ...predicate.Product) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProductMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProductMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Product, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProductMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProductMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Product).
func (m *ProductMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProductMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.title != nil {
		fields = append(fields, product.FieldTitle)
	}
	if m.reserved_by != nil {
		fields = append(fields, product.FieldReservedBy)
	}
	if m.image != nil {
		fields = append(fields, product.FieldImage)
	}
	if m.value != nil {
		fields = append(fields, product.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProductMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case product.FieldTitle:
		return m.Title()
	case product.FieldReservedBy:
		return m.ReservedBy()
	case product.FieldImage:
		return m.Image()
	case product.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProductMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case product.FieldTitle:
		return m.OldTitle(ctx)
	case product.FieldReservedBy:
		return m.OldReservedBy(ctx)
	case product.FieldImage:
		return m.OldImage(ctx)
	case product.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Product field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) SetField(name string, value ent.Value) error {
	switch name {
	case product.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case product.FieldReservedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReservedBy(v)
		return nil
	case product.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case product.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProductMutation) AddedFields() []string {
	var fields []string
	if m.addvalue != nil {
		fields = append(fields, product.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProductMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case product.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) AddField(name string, value ent.Value) error {
	switch name {
	case product.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown Product numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProductMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(product.FieldImage) {
		fields = append(fields, product.FieldImage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProductMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProductMutation) ClearField(name string) error {
	switch name {
	case product.FieldImage:
		m.ClearImage()
		return nil
	}
	return fmt.Errorf("unknown Product nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProductMutation) ResetField(name string) error {
	switch name {
	case product.FieldTitle:
		m.ResetTitle()
		return nil
	case product.FieldReservedBy:
		m.ResetReservedBy()
		return nil
	case product.FieldImage:
		m.ResetImage()
		return nil
	case product.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProductMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProductMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProductMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProductMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProductMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProductMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProductMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Product unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProductMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Product edge %s", name)
}
