// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding_api/ent/predicate"
	"wedding_api/ent/product"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProductUpdate) SetTitle(v string) *ProductUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableTitle(v *string) *ProductUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReservedBy sets the "reserved_by" field.
func (_u *ProductUpdate) SetReservedBy(v string) *ProductUpdate {
	_u.mutation.SetReservedBy(v)
	return _u
}

// SetNillableReservedBy sets the "reserved_by" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableReservedBy(v *string) *ProductUpdate {
	if v != nil {
		_u.SetReservedBy(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ProductUpdate) SetImage(v string) *ProductUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableImage(v *string) *ProductUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *ProductUpdate) ClearImage() *ProductUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetValor sets the "valor" field.
func (_u *ProductUpdate) SetValor(v float64) *ProductUpdate {
	_u.mutation.ResetValor()
	_u.mutation.SetValor(v)
	return _u
}

// SetNillableValor sets the "valor" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableValor(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetValor(*v)
	}
	return _u
}

// AddValor adds value to the "valor" field.
func (_u *ProductUpdate) AddValor(v float64) *ProductUpdate {
	_u.mutation.AddValor(v)
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedBy(); ok {
		_spec.SetField(product.FieldReservedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(product.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(product.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Valor(); ok {
		_spec.SetField(product.FieldValor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValor(); ok {
		_spec.AddField(product.FieldValor, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetTitle sets the "title" field.
func (_u *ProductUpdateOne) SetTitle(v string) *ProductUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableTitle(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReservedBy sets the "reserved_by" field.
func (_u *ProductUpdateOne) SetReservedBy(v string) *ProductUpdateOne {
	_u.mutation.SetReservedBy(v)
	return _u
}

// SetNillableReservedBy sets the "reserved_by" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableReservedBy(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetReservedBy(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ProductUpdateOne) SetImage(v string) *ProductUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableImage(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *ProductUpdateOne) ClearImage() *ProductUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetValor sets the "valor" field.
func (_u *ProductUpdateOne) SetValor(v float64) *ProductUpdateOne {
	_u.mutation.ResetValor()
	_u.mutation.SetValor(v)
	return _u
}

// SetNillableValor sets the "valor" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableValor(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetValor(*v)
	}
	return _u
}

// AddValor adds value to the "valor" field.
func (_u *ProductUpdateOne) AddValor(v float64) *ProductUpdateOne {
	_u.mutation.AddValor(v)
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedBy(); ok {
		_spec.SetField(product.FieldReservedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(product.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(product.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Valor(); ok {
		_spec.SetField(product.FieldValor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValor(); ok {
		_spec.AddField(product.FieldValor, field.TypeFloat64, value)
	}
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
