// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"wedding_api/ent/confirmationpresence"
	"wedding_api/ent/familyaccesstoken"
	"wedding_api/ent/schema"
	"wedding_api/ent/session"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	confirmationpresenceFields := schema.ConfirmationPresence{}.Fields()
	_ = confirmationpresenceFields
	// confirmationpresenceDescIsConfirmed is the schema descriptor for is_confirmed field.
	confirmationpresenceDescIsConfirmed := confirmationpresenceFields[2].Descriptor()
	// confirmationpresence.DefaultIsConfirmed holds the default value on creation for the is_confirmed field.
	confirmationpresence.DefaultIsConfirmed = confirmationpresenceDescIsConfirmed.Default.(bool)
	familyaccesstokenFields := schema.FamilyAccessToken{}.Fields()
	_ = familyaccesstokenFields
	// familyaccesstokenDescCreatedAt is the schema descriptor for created_at field.
	familyaccesstokenDescCreatedAt := familyaccesstokenFields[4].Descriptor()
	// familyaccesstoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	familyaccesstoken.DefaultCreatedAt = familyaccesstokenDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
}
