// Code generated by ent, DO NOT EDIT.

package confirmationpresence

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the confirmationpresence type in the database.
	Label = "confirmation_presence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFullname holds the string denoting the fullname field in the database.
	FieldFullname = "fullname"
	// FieldPhotoBase64 holds the string denoting the photo_base64 field in the database.
	FieldPhotoBase64 = "photo_base64"
	// FieldIsConfirmed holds the string denoting the is_confirmed field in the database.
	FieldIsConfirmed = "is_confirmed"
	// Table holds the table name of the confirmationpresence in the database.
	Table = "confirmation_presences"
)

// Columns holds all SQL columns for confirmationpresence fields.
var Columns = []string{
	FieldID,
	FieldFullname,
	FieldPhotoBase64,
	FieldIsConfirmed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsConfirmed holds the default value on creation for the "is_confirmed" field.
	DefaultIsConfirmed bool
)

// OrderOption defines the ordering options for the ConfirmationPresence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFullname orders the results by the fullname field.
func ByFullname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullname, opts...).ToFunc()
}

// ByPhotoBase64 orders the results by the photo_base64 field.
func ByPhotoBase64(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhotoBase64, opts...).ToFunc()
}

// ByIsConfirmed orders the results by the is_confirmed field.
func ByIsConfirmed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsConfirmed, opts...).ToFunc()
}
