// Code generated by ent, DO NOT EDIT.

package confirmationpresence

import (
	"wedding_api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLTE(FieldID, id))
}

// Fullname applies equality check predicate on the "fullname" field. It's identical to FullnameEQ.
func Fullname(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldFullname, v))
}

// PhotoBase64 applies equality check predicate on the "photo_base64" field. It's identical to PhotoBase64EQ.
func PhotoBase64(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldPhotoBase64, v))
}

// IsConfirmed applies equality check predicate on the "is_confirmed" field. It's identical to IsConfirmedEQ.
func IsConfirmed(v bool) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldIsConfirmed, v))
}

// FullnameEQ applies the EQ predicate on the "fullname" field.
func FullnameEQ(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldFullname, v))
}

// FullnameNEQ applies the NEQ predicate on the "fullname" field.
func FullnameNEQ(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNEQ(FieldFullname, v))
}

// FullnameIn applies the In predicate on the "fullname" field.
func FullnameIn(vs ...string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldIn(FieldFullname, vs...))
}

// FullnameNotIn applies the NotIn predicate on the "fullname" field.
func FullnameNotIn(vs ...string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNotIn(FieldFullname, vs...))
}

// FullnameGT applies the GT predicate on the "fullname" field.
func FullnameGT(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGT(FieldFullname, v))
}

// FullnameGTE applies the GTE predicate on the "fullname" field.
func FullnameGTE(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGTE(FieldFullname, v))
}

// FullnameLT applies the LT predicate on the "fullname" field.
func FullnameLT(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLT(FieldFullname, v))
}

// FullnameLTE applies the LTE predicate on the "fullname" field.
func FullnameLTE(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLTE(FieldFullname, v))
}

// FullnameContains applies the Contains predicate on the "fullname" field.
func FullnameContains(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldContains(FieldFullname, v))
}

// FullnameHasPrefix applies the HasPrefix predicate on the "fullname" field.
func FullnameHasPrefix(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldHasPrefix(FieldFullname, v))
}

// FullnameHasSuffix applies the HasSuffix predicate on the "fullname" field.
func FullnameHasSuffix(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldHasSuffix(FieldFullname, v))
}

// FullnameEqualFold applies the EqualFold predicate on the "fullname" field.
func FullnameEqualFold(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEqualFold(FieldFullname, v))
}

// FullnameContainsFold applies the ContainsFold predicate on the "fullname" field.
func FullnameContainsFold(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldContainsFold(FieldFullname, v))
}

// PhotoBase64EQ applies the EQ predicate on the "photo_base64" field.
func PhotoBase64EQ(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldPhotoBase64, v))
}

// PhotoBase64NEQ applies the NEQ predicate on the "photo_base64" field.
func PhotoBase64NEQ(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNEQ(FieldPhotoBase64, v))
}

// PhotoBase64In applies the In predicate on the "photo_base64" field.
func PhotoBase64In(vs ...string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldIn(FieldPhotoBase64, vs...))
}

// PhotoBase64NotIn applies the NotIn predicate on the "photo_base64" field.
func PhotoBase64NotIn(vs ...string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNotIn(FieldPhotoBase64, vs...))
}

// PhotoBase64GT applies the GT predicate on the "photo_base64" field.
func PhotoBase64GT(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGT(FieldPhotoBase64, v))
}

// PhotoBase64GTE applies the GTE predicate on the "photo_base64" field.
func PhotoBase64GTE(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldGTE(FieldPhotoBase64, v))
}

// PhotoBase64LT applies the LT predicate on the "photo_base64" field.
func PhotoBase64LT(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLT(FieldPhotoBase64, v))
}

// PhotoBase64LTE applies the LTE predicate on the "photo_base64" field.
func PhotoBase64LTE(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldLTE(FieldPhotoBase64, v))
}

// PhotoBase64Contains applies the Contains predicate on the "photo_base64" field.
func PhotoBase64Contains(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldContains(FieldPhotoBase64, v))
}

// PhotoBase64HasPrefix applies the HasPrefix predicate on the "photo_base64" field.
func PhotoBase64HasPrefix(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldHasPrefix(FieldPhotoBase64, v))
}

// PhotoBase64HasSuffix applies the HasSuffix predicate on the "photo_base64" field.
func PhotoBase64HasSuffix(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldHasSuffix(FieldPhotoBase64, v))
}

// PhotoBase64IsNil applies the IsNil predicate on the "photo_base64" field.
func PhotoBase64IsNil() predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldIsNull(FieldPhotoBase64))
}

// PhotoBase64NotNil applies the NotNil predicate on the "photo_base64" field.
func PhotoBase64NotNil() predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNotNull(FieldPhotoBase64))
}

// PhotoBase64EqualFold applies the EqualFold predicate on the "photo_base64" field.
func PhotoBase64EqualFold(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEqualFold(FieldPhotoBase64, v))
}

// PhotoBase64ContainsFold applies the ContainsFold predicate on the "photo_base64" field.
func PhotoBase64ContainsFold(v string) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldContainsFold(FieldPhotoBase64, v))
}

// IsConfirmedEQ applies the EQ predicate on the "is_confirmed" field.
func IsConfirmedEQ(v bool) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldEQ(FieldIsConfirmed, v))
}

// IsConfirmedNEQ applies the NEQ predicate on the "is_confirmed" field.
func IsConfirmedNEQ(v bool) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.FieldNEQ(FieldIsConfirmed, v))
}

// HasFamily applies the HasEdge predicate on the "family" edge.
func HasFamily() predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FamilyTable, FamilyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFamilyWith applies the HasEdge predicate on the "family" edge with a given conditions (other predicates).
func HasFamilyWith(preds ...predicate.Family) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(func(s *sql.Selector) {
		step := newFamilyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConfirmationPresence) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConfirmationPresence) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConfirmationPresence) predicate.ConfirmationPresence {
	return predicate.ConfirmationPresence(sql.NotPredicates(p))
}
